# Generated by Django 4.1.3 on 2022-12-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="./energy_tracker/static/assets/img/profile/",
            ),
        ),
    ]
