# Generated by Django 4.1.5 on 2023-01-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questioncategory_alter_question_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score_no',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score_yes',
        ),
    ]
