# Generated by Django 4.1.5 on 2023-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_score_no_remove_question_score_yes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score_no',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='score_yes',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
