# Generated by Django 4.1.3 on 2022-11-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
